modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "earthtojavamobs"
version = "1.10.2"
displayName = "Earth2Java"
authors = "Slexom"
description = "Bring mobs from Minecraft Earth to Minecraft Java Edition"
logoFile = "icon.png"

[[dependencies.earthtojavamobs]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthtojavamobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.earthtojavamobs]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "earthtojava-common.mixins.json"